<?xml version="1.0" encoding="utf-8" ?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    <Target Name="ILRepacker" AfterTargets="Build">
        <ItemGroup>
            <InputAssemblies Include="$(OutputPath)\XIVChat.dll"/>
            <InputAssemblies Include="$(OutputPath)\XIVChatCommon.dll"/>
            <InputAssemblies Include="$(OutputPath)\M*.dll"/>
            <InputAssemblies Include="$(OutputPath)\S*.dll"/>
        </ItemGroup>

        <ILRepack
                Parallel="true"
                Internalize="false"
                InputAssemblies="@(InputAssemblies)"
                TargetKind="Dll"
                TargetPlatformVersion="v4"
                LibraryPath="$(OutputPath)"
                OutputFile="$(OutputPath)\$(AssemblyName).dll"/>
    </Target>
</Project>
