<?xml version="1.0" encoding="utf-8" ?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    <Target Name="ILRepacker" AfterTargets="Build">
        <ItemGroup>
            <InputAssemblies Include="$(OutputPath)\$(AssemblyName).dll"/>
            <InputAssemblies Include="$(OutputPath)\*.dll"
                             Exclude="$(OutputPath)\$(AssemblyName).dll;
                                      $(OutputPath)\libsodium.dll;
                                      $(OutputPath)\xivchat_native_tools.dll;
                                      $(OutputPath)\System.Buffers.dll;
                                      $(OutputPath)\System.Memory.dll;
                                      $(OutputPath)\System.Numerics.Vectors.dll"/>
        </ItemGroup>

        <ILRepack
                Parallel="true"
                Internalize="false"
                InputAssemblies="@(InputAssemblies)"
                TargetKind="Dll"
                TargetPlatformVersion="v4"
                LibraryPath="$(OutputPath)"
                DebugInfo="true"
                OutputFile="$(OutputPath)\$(AssemblyName).dll"/>

        <Delete Files="@(ReferenceCopyLocalPaths->'$(OutDir)%(DestinationSubDirectory)%(Filename)%(Extension)')"/>
        <ItemGroup>
            <Directories Include="$([System.IO.Directory]::GetDirectories('$(OutDir)%(DestinationSubDirectory)', '*', System.IO.SearchOption.AllDirectories))"/>
            <Directories>
                <Files>$([System.IO.Directory]::GetFiles("%(Directories.Identity)", "*", System.IO.SearchOption.AllDirectories).get_Length())</Files>
            </Directories>
        </ItemGroup>
    </Target>
</Project>
