<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <RootNamespace>XIVChatPlugin</RootNamespace>
        <AssemblyName>XIVChat</AssemblyName>
        <TargetFramework>net48</TargetFramework>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>
        <Version>1.5.1</Version>
    </PropertyGroup>
    <ItemGroup>
        <Reference Include="Dalamud, Version=5.2.4.2, Culture=neutral, PublicKeyToken=null">
            <HintPath>$(AppData)\XIVLauncher\addon\Hooks\dev\Dalamud.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="ImGui.NET, Version=1.72.0.0, Culture=neutral, PublicKeyToken=null">
            <HintPath>$(AppData)\XIVLauncher\addon\Hooks\dev\ImGui.NET.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="ImGuiScene, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null">
            <HintPath>$(AppData)\XIVLauncher\addon\Hooks\dev\ImGuiScene.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="Lumina, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null">
            <HintPath>$(AppData)\XIVLauncher\addon\Hooks\dev\Lumina.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="Lumina.Excel, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null">
            <HintPath>$(AppData)\XIVLauncher\addon\Hooks\dev\Lumina.Excel.dll</HintPath>
            <Private>False</Private>
        </Reference>
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="DalamudPackager" Version="1.2.1"/>
        <PackageReference Include="ILRepack.Lib.MSBuild.Task" Version="2.0.18.2"/>
        <PackageReference Include="MessagePack" Version="2.2.85"/>
        <PackageReference Include="Sodium.Core" Version="1.2.3"/>
        <PackageReference Include="System.Threading.Channels" Version="5.0.0"/>
        <PackageReference Include="WebSocketSharp" Version="1.0.3-rc11"/>
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\XIVChatCommon\XIVChatCommon.csproj"/>
    </ItemGroup>
    <Target Name="CopyLibsodium" AfterTargets="AfterBuild">
        <Copy SourceFiles="Resources\lib\libsodium.dll" DestinationFolder="$(OutDir)"/>
    </Target>
</Project>
