<Project Sdk="Dalamud.NET.Sdk/15.0.0">
    <PropertyGroup>
        <RootNamespace>XIVChatPlugin</RootNamespace>
        <AssemblyName>EorzeaPhone</AssemblyName>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>
        <Version>0.3.7</Version>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
        <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
        <ProduceReferenceAssembly>false</ProduceReferenceAssembly>
        <DebugSymbols>true</DebugSymbols>
        <DebugType>full</DebugType>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="MessagePack" Version="3.1.4" />
        <PackageReference Include="PeepingTom.Ipc" Version="2.0.0" />
        <PackageReference Include="Sodium.Core" Version="1.4.0" />
        <PackageReference Include="System.Threading.Channels" Version="10.0.7" />
        <PackageReference Include="WebSocketSharp-netstandard" Version="1.0.1"/>
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\XIVChatCommon\XIVChatCommon.csproj"/>
        <None Include="EorzeaPhone.json" CopyToOutputDirectory="PreserveNewest" />
    </ItemGroup>
    <Target Name="CopyNativeLibraries" AfterTargets="AfterBuild">
        <Copy SourceFiles="Resources\lib\libsodium.dll" DestinationFolder="$(OutDir)"/>
        <Copy SourceFiles="Resources\lib\xivchat_native_tools.dll" DestinationFolder="$(OutDir)"/>
    </Target>
</Project>
