<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <RootNamespace>XIVChatPlugin</RootNamespace>
        <AssemblyName>XIVChat</AssemblyName>
        <TargetFramework>net48</TargetFramework>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>
        <Version>1.5.1</Version>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>
    <ItemGroup>
        <Reference Include="Dalamud">
            <HintPath>$(AppData)\XIVLauncher\addon\Hooks\dev\Dalamud.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="ImGui.NET">
            <HintPath>$(AppData)\XIVLauncher\addon\Hooks\dev\ImGui.NET.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="ImGuiScene">
            <HintPath>$(AppData)\XIVLauncher\addon\Hooks\dev\ImGuiScene.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="Lumina">
            <HintPath>$(AppData)\XIVLauncher\addon\Hooks\dev\Lumina.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="Lumina.Excel">
            <HintPath>$(AppData)\XIVLauncher\addon\Hooks\dev\Lumina.Excel.dll</HintPath>
            <Private>False</Private>
        </Reference>
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="DalamudPackager" Version="1.2.1" />
        <PackageReference Include="ILRepack.Lib.MSBuild.Task" Version="2.0.18.2" />
        <PackageReference Include="MessagePack" Version="2.2.85" />
        <PackageReference Include="Sodium.Core" Version="1.2.3" />
        <PackageReference Include="System.Threading.Channels" Version="5.0.0" />
        <PackageReference Include="WebSocketSharp" Version="1.0.3-rc11" />
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\XIVChatCommon\XIVChatCommon.csproj" />
    </ItemGroup>
    <Target Name="CopyNativeLibraries" AfterTargets="AfterBuild">
        <Copy SourceFiles="Resources\lib\libsodium.dll" DestinationFolder="$(OutDir)" />
        <Copy SourceFiles="Resources\lib\xivchat_native_tools.dll" DestinationFolder="$(OutDir)" />
    </Target>
</Project>
